//! GSDML (Generic Station Description Markup Language) parser, ported from
//! `gsdml.py`. Parses GSDML XML files to extract module catalogs and build
//! IO-slot lists for cyclic IO configuration, eliminating manual hardcoding
//! of device-specific module/submodule IDs and IO data sizes.
//!
//! Structural fidelity with the reference is verified against
//! `tests/golden/gsdml.json` (generated by `tools/gen_gsdml_golden.py`).

use std::collections::{BTreeMap, HashMap};
use std::path::Path;

use roxmltree::{Document, Node};

/// GSDML data type -> byte size (GSDML_TYPE_SIZES). None means the Length
/// attribute is required (variable-length types).
fn gsdml_type_size(data_type: &str) -> Option<usize> {
    match data_type {
        "Boolean" => Some(1),
        "Integer8" => Some(1),
        "Integer16" => Some(2),
        "Integer32" => Some(4),
        "Integer64" => Some(8),
        "Unsigned8" => Some(1),
        "Unsigned16" => Some(2),
        "Unsigned32" => Some(4),
        "Unsigned64" => Some(8),
        "Float32" => Some(4),
        "Float64" => Some(8),
        "TimeStamp" => Some(8),
        _ => None,
    }
}

/// Find first direct child element by local name, ignoring XML namespace.
fn find<'a, 'input>(elem: Node<'a, 'input>, local_name: &str) -> Option<Node<'a, 'input>> {
    elem.children()
        .find(|n| n.is_element() && n.tag_name().name() == local_name)
}

/// Find all direct child elements by local name, ignoring XML namespace.
fn findall<'a, 'input>(
    elem: Node<'a, 'input>,
    local_name: &'a str,
) -> impl Iterator<Item = Node<'a, 'input>> {
    elem.children()
        .filter(move |n| n.is_element() && n.tag_name().name() == local_name)
}

/// Find first descendant element by local name, ignoring XML namespace.
fn find_deep<'a, 'input>(elem: Node<'a, 'input>, local_name: &str) -> Option<Node<'a, 'input>> {
    elem.descendants()
        .find(|n| n.is_element() && n.tag_name().name() == local_name)
}

/// Find all descendant elements by local name, ignoring XML namespace.
fn findall_deep<'a, 'input>(
    elem: Node<'a, 'input>,
    local_name: &'a str,
) -> impl Iterator<Item = Node<'a, 'input>> {
    elem.descendants()
        .filter(move |n| n.is_element() && n.tag_name().name() == local_name)
}

/// Parse an integer attribute, supporting the 0x hex prefix (_parse_int).
/// A missing attribute parses as 0, as in the reference.
fn parse_int(value: Option<&str>) -> Result<u32, String> {
    let Some(value) = value else {
        return Ok(0);
    };
    let value = value.trim();
    let parsed = if let Some(hex) = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
    {
        u32::from_str_radix(hex, 16)
    } else {
        value.parse()
    };
    parsed.map_err(|e| format!("invalid integer {value:?}: {e}"))
}

/// Parse total IO data size in bytes for a direction ('Input'/'Output') from
/// a VirtualSubmoduleItem element (_parse_io_data_size).
fn parse_io_data_size(submodule_elem: Node, direction: &str) -> Result<usize, String> {
    let Some(io_data) = find(submodule_elem, "IOData") else {
        return Ok(0);
    };
    let Some(dir_elem) = find(io_data, direction) else {
        return Ok(0);
    };
    // One PROFINET cyclic frame carries far less than this; a hostile GSDML with
    // huge/many Length attrs must not overflow (panic in debug, silent wrap in
    // release) the accumulator that then sizes the IOCR.
    const MAX_IO_DATA_LEN: usize = 0x1_0000;
    let mut total = 0usize;
    for data_item in findall(dir_elem, "DataItem") {
        let add = if let Some(length_attr) = data_item.attribute("Length") {
            length_attr
                .parse::<usize>()
                .map_err(|e| format!("invalid Length {length_attr:?}: {e}"))?
        } else {
            gsdml_type_size(data_item.attribute("DataType").unwrap_or("")).unwrap_or_default()
        };
        total = total
            .checked_add(add)
            .filter(|&t| t <= MAX_IO_DATA_LEN)
            .ok_or_else(|| {
                format!("IOData {direction} length exceeds the {MAX_IO_DATA_LEN}-byte cap")
            })?;
    }
    Ok(total)
}

/// Parse a GSDML slot spec like "1..3" or "1 2 5" into a list (_parse_slot_spec).
fn parse_slot_spec(spec: Option<&str>) -> Result<Vec<u16>, String> {
    let Some(spec) = spec else {
        return Ok(Vec::new());
    };
    // A hostile GSDML with wide ranges (e.g. "0..65535" x N refs) would otherwise
    // materialize tens of millions of u16s. Real GSDMLs list a handful of slots.
    const MAX_SLOTS: usize = 4096;
    let mut result: Vec<u16> = Vec::new();
    for part in spec.replace(',', " ").split_whitespace() {
        let parse = |s: &str| {
            s.parse::<u16>()
                .map_err(|e| format!("invalid slot spec part {part:?}: {e}"))
        };
        if let Some((start, end)) = part.split_once("..") {
            let (start, end) = (parse(start)?, parse(end)?);
            let span = usize::from(end.saturating_sub(start)) + 1;
            if end >= start && result.len() + span > MAX_SLOTS {
                return Err(format!(
                    "slot spec {part:?} expands beyond the {MAX_SLOTS}-slot cap"
                ));
            }
            result.extend(start..=end);
        } else {
            if result.len() >= MAX_SLOTS {
                return Err(format!("slot spec exceeds the {MAX_SLOTS}-slot cap"));
            }
            result.push(parse(part)?);
        }
    }
    Ok(result)
}

/// A GSDML virtual submodule definition (GSDMLSubmodule).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GsdmlSubmodule {
    pub id: String,
    pub submodule_ident: u32,
    pub input_length: usize,
    pub output_length: usize,
}

/// One ModuleItemRef/SubmoduleItemRef: the reference keeps these as three
/// parallel dicts (useable/fixed/allowed keyed by target); here they are one
/// list of refs in document order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ItemRef {
    /// Referenced ModuleItemTarget / SubmoduleItemTarget ID.
    pub target: String,
    /// FixedInSlots / FixedInSubslots.
    pub fixed: Vec<u16>,
    /// AllowedInSlots / AllowedInSubslots.
    pub allowed: Vec<u16>,
}

/// A GSDML module definition from ModuleList (GSDMLModule).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GsdmlModule {
    pub id: String,
    pub module_ident: u32,
    /// Inline VirtualSubmoduleList entries.
    pub submodules: Vec<GsdmlSubmodule>,
    /// UseableSubmodules: references to top-level SubmoduleList entries.
    pub useable_submodules: Vec<ItemRef>,
}

/// A system-defined submodule, interface or port (GSDMLSystemSubmodule).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GsdmlSystemSubmodule {
    pub subslot_number: u16,
    pub submodule_ident: u32,
}

/// Device Access Point configuration (GSDMLDAP).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GsdmlDap {
    pub id: String,
    pub module_ident: u32,
    pub submodules: Vec<GsdmlSubmodule>,
    pub system_submodules: Vec<GsdmlSystemSubmodule>,
    /// UseableModules refs with their FixedInSlots/AllowedInSlots.
    pub useable_modules: Vec<ItemRef>,
}

/// Single IO slot/subslot for cyclic data exchange (IOSlot), as consumed by
/// IOCR setup / a future connect module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IoSlot {
    pub slot: u16,
    pub subslot: u16,
    /// Module identification number.
    pub module_ident: u32,
    /// Submodule identification number.
    pub submodule_ident: u32,
    /// Input data length in bytes (device -> controller). 0 = no input.
    pub input_length: usize,
    /// Output data length in bytes (controller -> device). 0 = no output.
    pub output_length: usize,
}

/// Slot/subslot discovered from a device (SlotInfo view), the input to
/// [`GsdmlDevice::build_io_slots_from_device`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeviceSlot {
    pub slot: u16,
    pub subslot: u16,
    pub module_ident: u32,
    pub submodule_ident: u32,
}

/// Parsed GSDML device description with module catalog (GSDMLDevice).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GsdmlDevice {
    pub vendor_id: u16,
    pub device_id: u16,
    pub daps: Vec<GsdmlDap>,
    /// ModuleList entries in document order (dict in the reference).
    pub modules: Vec<GsdmlModule>,
    /// Top-level SubmoduleList entries (referenced by UseableSubmodules).
    pub submodule_catalog: Vec<GsdmlSubmodule>,
}

impl GsdmlDevice {
    /// Get DAP by ID, or the first DAP if `dap_id` is None (get_dap).
    pub fn get_dap(&self, dap_id: Option<&str>) -> Result<&GsdmlDap, String> {
        if self.daps.is_empty() {
            return Err("No DAP found in GSDML".to_string());
        }
        match dap_id {
            None => Ok(&self.daps[0]),
            Some(id) => self
                .daps
                .iter()
                .find(|d| d.id == id)
                .ok_or_else(|| format!("DAP '{id}' not found")),
        }
    }

    fn module(&self, id: &str) -> Option<&GsdmlModule> {
        self.modules.iter().find(|m| m.id == id)
    }

    fn catalog_submodule(&self, id: &str) -> Option<&GsdmlSubmodule> {
        self.submodule_catalog.iter().find(|s| s.id == id)
    }

    /// Build the IoSlot list from the GSDML module catalog (build_io_slots).
    ///
    /// * `slot_assignment`: explicit slot number -> module ID mapping; if
    ///   None, uses FixedInSlots from UseableModules.
    /// * `submodule_assignment`: for modules using UseableSubmodules, slot
    ///   number -> (subslot number -> submodule ID); FixedInSubslots are
    ///   always included automatically.
    /// * `dap_id`: DAP to use; if None, uses the first DAP.
    pub fn build_io_slots(
        &self,
        slot_assignment: Option<&BTreeMap<u16, String>>,
        submodule_assignment: Option<&BTreeMap<u16, BTreeMap<u16, String>>>,
        dap_id: Option<&str>,
    ) -> Result<Vec<IoSlot>, String> {
        let dap = self.get_dap(dap_id)?;
        let mut slots = Vec::new();

        // DAP virtual submodules at slot 0.
        for (i, sub) in dap.submodules.iter().enumerate() {
            slots.push(IoSlot {
                slot: 0,
                subslot: i as u16 + 1,
                module_ident: dap.module_ident,
                submodule_ident: sub.submodule_ident,
                input_length: sub.input_length,
                output_length: sub.output_length,
            });
        }

        // System submodules (interface/ports) at slot 0.
        for sys_sub in &dap.system_submodules {
            slots.push(IoSlot {
                slot: 0,
                subslot: sys_sub.subslot_number,
                module_ident: dap.module_ident,
                submodule_ident: sys_sub.submodule_ident,
                input_length: 0,
                output_length: 0,
            });
        }

        // Determine slot assignment (BTreeMap iteration = sorted(assignment)).
        let assignment: BTreeMap<u16, String> = match slot_assignment {
            Some(a) => a.clone(),
            None => dap
                .useable_modules
                .iter()
                .flat_map(|r| r.fixed.iter().map(|&slot| (slot, r.target.clone())))
                .collect(),
        };
        let empty = BTreeMap::new();

        // Add module slots.
        for (&slot_num, mod_id) in &assignment {
            let Some(module) = self.module(mod_id) else {
                continue;
            };
            if !module.submodules.is_empty() {
                // Module has an inline VirtualSubmoduleList.
                for (i, sub) in module.submodules.iter().enumerate() {
                    slots.push(IoSlot {
                        slot: slot_num,
                        subslot: i as u16 + 1,
                        module_ident: module.module_ident,
                        submodule_ident: sub.submodule_ident,
                        input_length: sub.input_length,
                        output_length: sub.output_length,
                    });
                }
            } else if !module.useable_submodules.is_empty() {
                // Module uses UseableSubmodules referencing the catalog.
                let subslot_assign = submodule_assignment
                    .and_then(|a| a.get(&slot_num))
                    .unwrap_or(&empty);
                self.add_useable_submodule_slots(&mut slots, module, slot_num, subslot_assign);
            }
        }

        Ok(slots)
    }

    /// Resolve UseableSubmodules for a module and add IoSlots
    /// (_add_useable_submodule_slots).
    fn add_useable_submodule_slots(
        &self,
        slots: &mut Vec<IoSlot>,
        module: &GsdmlModule,
        slot_num: u16,
        subslot_assign: &BTreeMap<u16, String>,
    ) {
        // Collect subslot -> submodule ID; FixedInSubslots are always
        // included, user-provided assignments override them.
        let mut resolved: BTreeMap<u16, &str> = BTreeMap::new();
        for item_ref in &module.useable_submodules {
            for &subslot_num in &item_ref.fixed {
                resolved.insert(subslot_num, &item_ref.target);
            }
        }
        for (&subslot_num, sub_id) in subslot_assign {
            resolved.insert(subslot_num, sub_id);
        }

        for (&subslot_num, sub_id) in &resolved {
            let Some(cat_sub) = self.catalog_submodule(sub_id) else {
                continue;
            };
            slots.push(IoSlot {
                slot: slot_num,
                subslot: subslot_num,
                module_ident: module.module_ident,
                submodule_ident: cat_sub.submodule_ident,
                input_length: cat_sub.input_length,
                output_length: cat_sub.output_length,
            });
        }
    }

    /// Build the IoSlot list by matching runtime slot discovery against the
    /// GSDML catalog (build_io_slots_from_device): IO sizes are filled from
    /// the catalog, unknown ident pairs get length 0.
    pub fn build_io_slots_from_device(
        &self,
        device_slots: &[DeviceSlot],
        dap_id: Option<&str>,
    ) -> Result<Vec<IoSlot>, String> {
        let dap = self.get_dap(dap_id)?;

        // module_ident -> submodule_ident -> (input_len, output_len).
        let mut ident_lookup: HashMap<u32, HashMap<u32, (usize, usize)>> = HashMap::new();

        // DAP submodules.
        for sub in &dap.submodules {
            ident_lookup
                .entry(dap.module_ident)
                .or_default()
                .insert(sub.submodule_ident, (sub.input_length, sub.output_length));
        }

        // System submodules (no IO data).
        for sys_sub in &dap.system_submodules {
            ident_lookup
                .entry(dap.module_ident)
                .or_default()
                .insert(sys_sub.submodule_ident, (0, 0));
        }

        // All catalog modules (inline submodules).
        for module in &self.modules {
            for sub in &module.submodules {
                ident_lookup
                    .entry(module.module_ident)
                    .or_default()
                    .insert(sub.submodule_ident, (sub.input_length, sub.output_length));
            }
            // Modules with UseableSubmodules: register catalog entries under
            // the module ident.
            for item_ref in &module.useable_submodules {
                if let Some(cat_sub) = self.catalog_submodule(&item_ref.target) {
                    ident_lookup.entry(module.module_ident).or_default().insert(
                        cat_sub.submodule_ident,
                        (cat_sub.input_length, cat_sub.output_length),
                    );
                }
            }
        }

        Ok(device_slots
            .iter()
            .map(|ds| {
                let (input_length, output_length) = ident_lookup
                    .get(&ds.module_ident)
                    .and_then(|subs| subs.get(&ds.submodule_ident))
                    .copied()
                    .unwrap_or((0, 0));
                IoSlot {
                    slot: ds.slot,
                    subslot: ds.subslot,
                    module_ident: ds.module_ident,
                    submodule_ident: ds.submodule_ident,
                    input_length,
                    output_length,
                }
            })
            .collect())
    }
}

/// Parse a VirtualSubmoduleItem / SubmoduleItem element (_parse_submodule).
fn parse_submodule(elem: Node) -> Result<GsdmlSubmodule, String> {
    Ok(GsdmlSubmodule {
        id: elem.attribute("ID").unwrap_or("").to_string(),
        submodule_ident: parse_int(elem.attribute("SubmoduleIdentNumber"))?,
        input_length: parse_io_data_size(elem, "Input")?,
        output_length: parse_io_data_size(elem, "Output")?,
    })
}

/// Parse a VirtualSubmoduleList from a parent element (_parse_virtual_submodules).
fn parse_virtual_submodules(parent: Node) -> Result<Vec<GsdmlSubmodule>, String> {
    let Some(vsl) = find(parent, "VirtualSubmoduleList") else {
        return Ok(Vec::new());
    };
    findall(vsl, "VirtualSubmoduleItem")
        .map(parse_submodule)
        .collect()
}

/// Parse the SystemDefinedSubmoduleList from a DAP element
/// (_parse_system_submodules).
fn parse_system_submodules(dap_elem: Node) -> Result<Vec<GsdmlSystemSubmodule>, String> {
    let Some(sdsl) = find(dap_elem, "SystemDefinedSubmoduleList") else {
        return Ok(Vec::new());
    };
    let mut result = Vec::new();
    for tag in ["InterfaceSubmoduleItem", "PortSubmoduleItem"] {
        for item in findall(sdsl, tag) {
            result.push(GsdmlSystemSubmodule {
                subslot_number: parse_int(item.attribute("SubslotNumber"))? as u16,
                submodule_ident: parse_int(item.attribute("SubmoduleIdentNumber"))?,
            });
        }
    }
    Ok(result)
}

/// Parse UseableModules / UseableSubmodules item refs (_parse_useable_modules
/// and _parse_useable_submodules share this shape).
fn parse_item_refs(
    parent: Node,
    list_tag: &str,
    ref_tag: &str,
    target_attr: &str,
    fixed_attr: &str,
    allowed_attr: &str,
) -> Result<Vec<ItemRef>, String> {
    let Some(list) = find(parent, list_tag) else {
        return Ok(Vec::new());
    };
    let mut refs = Vec::new();
    for item in findall(list, ref_tag) {
        refs.push(ItemRef {
            target: item.attribute(target_attr).unwrap_or("").to_string(),
            fixed: parse_slot_spec(item.attribute(fixed_attr))?,
            allowed: parse_slot_spec(item.attribute(allowed_attr))?,
        });
    }
    Ok(refs)
}

/// Parse a GSDML XML document root into a GsdmlDevice (_parse_gsdml_root).
fn parse_gsdml_root(root: Node) -> Result<GsdmlDevice, String> {
    let mut device = GsdmlDevice::default();

    // DeviceIdentity
    if let Some(dev_ident) = find_deep(root, "DeviceIdentity") {
        device.vendor_id = parse_int(dev_ident.attribute("VendorID"))? as u16;
        device.device_id = parse_int(dev_ident.attribute("DeviceID"))? as u16;
    }

    // Top-level SubmoduleList (referenced by UseableSubmodules)
    for sub_elem in findall_deep(root, "SubmoduleItem") {
        device.submodule_catalog.push(parse_submodule(sub_elem)?);
    }

    // DeviceAccessPointList
    for dap_elem in findall_deep(root, "DeviceAccessPointItem") {
        device.daps.push(GsdmlDap {
            id: dap_elem.attribute("ID").unwrap_or("").to_string(),
            module_ident: parse_int(dap_elem.attribute("ModuleIdentNumber"))?,
            submodules: parse_virtual_submodules(dap_elem)?,
            system_submodules: parse_system_submodules(dap_elem)?,
            useable_modules: parse_item_refs(
                dap_elem,
                "UseableModules",
                "ModuleItemRef",
                "ModuleItemTarget",
                "FixedInSlots",
                "AllowedInSlots",
            )?,
        });
    }

    // ModuleList
    for mod_elem in findall_deep(root, "ModuleItem") {
        device.modules.push(GsdmlModule {
            id: mod_elem.attribute("ID").unwrap_or("").to_string(),
            module_ident: parse_int(mod_elem.attribute("ModuleIdentNumber"))?,
            submodules: parse_virtual_submodules(mod_elem)?,
            useable_submodules: parse_item_refs(
                mod_elem,
                "UseableSubmodules",
                "SubmoduleItemRef",
                "SubmoduleItemTarget",
                "FixedInSubslots",
                "AllowedInSubslots",
            )?,
        });
    }

    Ok(device)
}

/// Parse GSDML XML text into a GsdmlDevice.
pub fn parse_gsdml_str(xml: &str) -> Result<GsdmlDevice, String> {
    let doc = Document::parse(xml).map_err(|e| format!("malformed GSDML XML: {e}"))?;
    parse_gsdml_root(doc.root_element())
}

/// Parse a GSDML XML file into a GsdmlDevice with full module catalog
/// (load_gsdml). GSDML files commonly declare iso-8859-1; non-UTF-8 input is
/// decoded as Latin-1.
pub fn load_gsdml<P: AsRef<Path>>(path: P) -> Result<GsdmlDevice, String> {
    let path = path.as_ref();
    let bytes = std::fs::read(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let text = match String::from_utf8(bytes) {
        Ok(s) => s,
        // Latin-1 maps every byte to the same Unicode code point.
        Err(e) => e.as_bytes().iter().map(|&b| b as char).collect(),
    };
    parse_gsdml_str(&text)
}

/// Parse a GSDML file and build the IoSlot list with the GSDML's FixedInSlots
/// defaults (parse_gsdml shortcut).
pub fn parse_gsdml<P: AsRef<Path>>(
    path: P,
    slot_assignment: Option<&BTreeMap<u16, String>>,
) -> Result<Vec<IoSlot>, String> {
    load_gsdml(path)?.build_io_slots(slot_assignment, None, None)
}

#[cfg(test)]
mod hardening_tests {
    use super::*;

    #[test]
    fn parse_slot_spec_caps_range_expansion() {
        // A wide range must be rejected, not materialized into millions of u16s.
        assert!(parse_slot_spec(Some("0..65535")).is_err());
        // Normal specs still parse.
        assert_eq!(parse_slot_spec(Some("1..3")).unwrap(), vec![1, 2, 3]);
        assert_eq!(parse_slot_spec(Some("1 2 5")).unwrap(), vec![1, 2, 5]);
        assert_eq!(parse_slot_spec(None).unwrap(), Vec::<u16>::new());
        // A reversed range stays empty (unchanged behaviour), no error.
        assert_eq!(parse_slot_spec(Some("5..1")).unwrap(), Vec::<u16>::new());
    }

    #[test]
    fn parse_io_data_size_rejects_overflowing_length() {
        // Two i64::MAX Lengths overflowed `total` (panic in debug / wrap in
        // release) before the checked_add + cap.
        let xml = r#"<VirtualSubmoduleItem><IOData><Input>
            <DataItem Length="9223372036854775807"/>
            <DataItem Length="9223372036854775807"/>
        </Input></IOData></VirtualSubmoduleItem>"#;
        let doc = roxmltree::Document::parse(xml).unwrap();
        let err = parse_io_data_size(doc.root_element(), "Input").unwrap_err();
        assert!(err.contains("cap"), "got: {err}");
    }

    #[test]
    fn parse_io_data_size_accepts_normal_lengths() {
        let xml = r#"<VirtualSubmoduleItem><IOData><Input>
            <DataItem Length="4"/><DataItem Length="2"/>
        </Input></IOData></VirtualSubmoduleItem>"#;
        let doc = roxmltree::Document::parse(xml).unwrap();
        assert_eq!(parse_io_data_size(doc.root_element(), "Input").unwrap(), 6);
    }
}
