//! profinet-rs: a PROFINET IO-controller, ported 1:1 from the Python
//! reference implementation `f0rw4rd/profinet-py` (GPL-3.0). As a translation
//! it is a derivative work and is therefore also GPL-3.0.
//!
//! Byte-for-byte fidelity with the reference is verified by golden vectors
//! generated by `tools/gen_golden.py` (see `tests/golden/`).
//!
//! Modules are ported bottom-up: util/wire -> blocks -> rpc -> dcp -> rt ->
//! cyclic -> gsdml -> cli.

// Modules are added as they are ported.

pub mod alarm_listener;
pub mod alarms;
pub mod blocks;
pub mod capture_check;
pub mod connect;
pub mod cyclic;
pub mod dcp;
pub mod device;
pub mod diagnosis;
pub mod epm;
pub mod errors;
pub mod gsdml;
pub mod im;
pub mod indices;
pub mod pcap;
pub mod rawudp;
pub mod rpc;
pub mod rt;
pub mod transport;
pub mod util;
pub mod vendors;
